name: Build wheel test
on: push
jobs:
  build:
    name: Build wheel test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install and upgrade pip and wheel
      run: >-
        python -m
        pip install -U
        pip wheel
        --user
    - name: Install setuptools
      run: >-
        python -m
        pip install -U
        setuptools
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python
        setup.py
        sdist
        bdist_wheel